export interface OverlayStatus {
  active: boolean;
  alwaysOnTop: boolean;
  clickThrough: boolean;
  transparent: boolean;
  overlayActive: boolean;
  alwaysOnTopEnabled: boolean;
  clickThroughEnabled: boolean;
  transparentEnabled: boolean;
  lastError?: string;
}

export type NativeWallpaperBackend =
  | 'fallback_stage'
  | 'none'
  | 'progman_native_host_probe'
  | 'workerw_native_host_probe'
  | 'workerw_child_native_host_probe'
  | 'web_preview'
  | 'electron_window'
  | 'native_desktop_wallpaper';

export interface NativeWallpaperResult {
  ok: boolean;
  mode: 'native_desktop_wallpaper' | 'fallback_stage' | 'unsupported';
  message?: string;
}

export interface NativeWallpaperStatus {
  active: boolean;
  appVersion?: string;
  attached?: boolean;
  attachMethod?: string;
  backend: NativeWallpaperBackend;
  electronWallpaperHwnd?: string;
  fallbackActive?: boolean;
  fallbackReason?: string;
  helperAvailable?: boolean;
  helperLastResult?: string;
  helperPath?: string | null;
  helperPid?: number;
  helperProcessAlive?: boolean;
  helperRunning?: boolean;
  helperVersion?: string;
  hostHwnd?: string;
  activeDisplaySurfaces?: string[];
  appScreen?: string;
  clickThroughEnabled?: boolean;
  clickThroughMode?: string;
  cleanupStaleHostWindowsAttempted?: boolean;
  cleanupStaleHostWindowsFailed?: boolean;
  cleanupStaleHostWindowsSucceeded?: boolean;
  coordinateMode?: string;
  electronIgnoreMouseEventsEnabled?: boolean;
  electronIgnoreMouseEventsRequested?: boolean;
  electronParentHwndAfterSetParent?: string | null;
  hostWindowRect?: unknown;
  hostParentHwndAfterSetParent?: string | null;
  hostRectAfterSetParent?: unknown;
  hostRectAfterSetWindowPos?: unknown;
  hostRectBeforeSetParent?: unknown;
  hostRelativeToShellDllDefView?: string;
  hostRelativeToSysListView32?: string;
  lastError?: string;
  nativeAttached?: boolean;
  nativeExStyleAfterClickThrough?: string;
  nativeExStyleBeforeClickThrough?: string;
  nativeHostHwnd?: string;
  nativeHostNoActivateEnabled?: boolean;
  nativeHostNoActivateRequested?: boolean;
  nativeHostTransparentEnabled?: boolean;
  nativeHostTransparentRequested?: boolean;
  nativeProbeActive?: boolean;
  nativeProbeBackend?: string;
  nativeProbeVisible?: boolean;
  renderSurface?: 'main_window' | 'wallpaper_stage' | 'native_wallpaper_surface' | 'overlay' | string;
  nativeWallpaperSurface?: boolean;
  controlView?: boolean;
  nativeWallpaperSurfaceInteractiveUiVisible?: boolean;
  nativeWallpaperSurfaceButtonsVisible?: boolean;
  nativeWallpaperSurfaceExitButtonVisible?: boolean;
  controlViewExitButtonVisible?: boolean;
  controlViewVisible?: boolean;
  controlViewDiagnosticsVisible?: boolean;
  controlViewModeSelectorVisible?: boolean;
  controlViewMode?: string;
  controlViewMovable?: boolean;
  controlViewDraggable?: boolean;
  controlViewMinimizeButtonVisible?: boolean;
  controlViewCloseButtonVisible?: boolean;
  controlViewCloseAction?: string;
  controlViewMinimized?: boolean;
  controlViewBounds?: unknown;
  controlViewRestoreTargetScreen?: unknown;
  savedMainWindowBoundsBeforeNativeWallpaper?: unknown;
  savedMainWindowStateBeforeNativeWallpaper?: unknown;
  savedMenuBarVisibleBeforeNativeWallpaper?: boolean;
  controlViewWindowResized?: boolean;
  controlViewWindowResizeReason?: string;
  controlViewMenuBarVisible?: boolean;
  menuBarSuppressedForControlView?: boolean;
  controlViewLayoutCompact?: boolean;
  controlViewLargeBlankSuppressed?: boolean;
  mainGameLayoutMounted?: boolean;
  wallpaperStageLayoutMounted?: boolean;
  nativeWallpaperControlViewMounted?: boolean;
  nativeWallpaperControlWindowCreated?: boolean;
  nativeWallpaperControlWindowVisible?: boolean;
  nativeWallpaperControlWindowBounds?: unknown;
  nativeWallpaperControlWindowFrameless?: boolean;
  nativeWallpaperControlWindowDraggable?: boolean;
  nativeWallpaperControlWindowRoute?: string;
  nativeWallpaperControlWindowButtonCount?: number;
  duplicateControlButtonsDetected?: boolean;
  mainWindowHiddenForNativeWallpaper?: boolean;
  mainWindowRestoredAfterNativeWallpaper?: boolean;
  restoredMainWindowBoundsAfterNativeWallpaper?: unknown;
  restoredMainWindowStateAfterNativeWallpaper?: unknown;
  restoreMainWindowReason?: string;
  controlViewWindowBounds?: unknown;
  mainWindowBounds?: unknown;
  mainWindowCoversPrimaryScreen?: boolean;
  mainWindowMayBlockDesktopClicks?: boolean;
  controlViewTransparentOrEmptySuspected?: boolean;
  desktopIconClickThroughExpected?: boolean;
  desktopIconClickThroughBlockedSuspected?: boolean;
  wallpaperWindowMayBlockDesktopClicks?: boolean;
  controlViewMayBlockDesktopClicks?: boolean;
  electronWallpaperIgnoreMouseEventsEnabled?: boolean;
  nativeHostToolWindowEnabled?: boolean;
  previousAppScreenBeforeNativeWallpaper?: string;
  restoredAppScreenAfterNativeWallpaperOff?: string;
  nativeWallpaperChangedAppScreen?: boolean;
  mainWindowGameCanvasSuppressed?: boolean;
  mainWindowGameCanvasSuppressionReason?: string;
  normalGameCanvasVisible?: boolean;
  normalBackgroundVisible?: boolean;
  normalMuseVisible?: boolean;
  wallpaperSurfaceClickThroughExpected?: boolean;
  wallpaperSurfaceUiSuppressed?: boolean;
  wallpaperSurfaceUiSuppressionReason?: string;
  fallbackStageVisible?: boolean;
  overlayVisible?: boolean;
  mainStageVisible?: boolean;
  duplicateStageSuppressed?: boolean;
  duplicateStageSuppressionReason?: string;
  needsManualVerification?: boolean;
  parentHwndAfterSetParent?: string | null;
  closestWorkerWHwnd?: string;
  closestWorkerWReason?: string;
  preferredWorkerWHwnd?: string | null;
  preferredReason?: string;
  previousParentHwnd?: string;
  probeAttached?: boolean;
  progmanCandidate?: unknown;
  progmanCoversPrimaryScreen?: boolean;
  progmanFound?: boolean;
  progmanHasShellDllDefView?: boolean;
  progmanHasSysListView32?: boolean;
  progmanHwnd?: string;
  progmanNativeHostHwnd?: string;
  progmanNativeHostProbeResult?: unknown;
  progmanChildrenAfterHostCreate?: unknown[];
  progmanChildrenAfterSetParent?: unknown[];
  progmanChildrenAfterZOrder?: unknown[];
  progmanChildrenBeforeProbe?: unknown[];
  progmanChildWorkerWCandidates?: unknown[];
  progmanProbeAttempted?: boolean;
  requestedParentClientRect?: unknown;
  requestedScreenRect?: unknown;
  progmanClientRect?: unknown;
  progmanWindowRect?: unknown;
  rectMismatch?: boolean;
  reason?: string;
  restoredAfterProbe?: boolean;
  setParentResult?: string | null;
  setParentSucceeded?: boolean;
  setWindowPosSucceeded?: boolean;
  shellDllDefViewFound?: boolean;
  shellDllDefViewHwnd?: string;
  supported: boolean;
  sysListView32Hwnd?: string;
  hitTestTransparentIfImplemented?: boolean;
  virtualScreenRect?: unknown;
  wallpaperWindowRect?: unknown;
  wallpaperRectAfterSetParent?: unknown;
  wallpaperRectAfterSetWindowPos?: unknown;
  staleHostWindowsBeforeCleanup?: unknown[];
  workerWDiscoveryStrategies?: unknown[];
  workerWChildHwnd?: string;
  workerWChildNativeHostProbeHwnd?: string;
  workerWChildNativeHostProbeResult?: unknown;
  workerWNativeHostProbeHwnd?: string;
  workerWNativeHostProbeResult?: unknown;
  workerWProbeAttempted?: boolean;
  zOrderResult?: string;
  zOrderStrategy?: string;
  zOrderStrategyResults?: unknown[];
  zOrderSucceeded?: boolean;
  selectedProgmanChildWorkerWHwnd?: string;
  selectedWorkerWHwnd?: string;
  selectedWorkerWStrategy?: string;
  workerWHwnd?: string;
  workerWCandidates?: unknown[];
  workerWCandidatesBeforeMessage?: unknown[];
  workerWCandidateCount?: number;
  workerWCreatedHwnds?: string[];
  workerWRemovedHwnds?: string[];
  workerWSelectionOrder?: unknown[];
  warnings?: string[];
  dryRun?: boolean;
}

export interface PlatformAdapter {
  readonly platformId: 'electron' | 'local' | 'steam';
  enterOverlayMode?: () => Promise<void>;
  exitOverlayMode?: () => Promise<void>;
  enterNativeWallpaperMode?: () => Promise<NativeWallpaperResult>;
  exitNativeWallpaperMode?: () => Promise<NativeWallpaperResult>;
  minimizeNativeWallpaperControlView?: () => Promise<{ ok: boolean; minimized?: boolean; reason?: string }>;
  getNativeWallpaperStatus?: () => Promise<NativeWallpaperStatus>;
  getOverlayStatus?: () => Promise<OverlayStatus>;
  setAlwaysOnTop?: (enabled: boolean) => Promise<void>;
  setClickThrough?: (enabled: boolean) => Promise<void>;
  setTransparentWindow?: (enabled: boolean) => Promise<void>;
  onOverlayExitRequested?: (callback: () => void) => () => void;
  onOverlayState?: (callback: (state: OverlayStatus) => void) => () => void;
  onNativeWallpaperStatus?: (callback: (state: NativeWallpaperStatus) => void) => () => void;
}
